export const authStyle = {
  container: {
    flex: 1,
    justifyContent: 'center',
    padding: 20,
    backgroundColor: '#f9f9f9',
  },
  header: {
    fontSize: 28,
    fontWeight: 'bold',
    marginBottom: 20,
    color: '#333',
    textAlign: 'center',
  },
  textInput: {
    marginBottom: 12,
    padding: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ddd',
    backgroundColor: '#fff',
    fontSize: 16,
  },
  button: {
    marginTop: 10,
    borderRadius: 8,
    backgroundColor: '#BF8ED4',
    borderColor: 'd0f4de',
    paddingVertical: 12,
    alignItems: 'center',
  },
  secondaryButton: {
    marginTop: 10,
    borderWidth: 1,
    borderRadius: 8,
    borderColor: '#BF8ED4',
    backgroundColor: '#fff',
    paddingVertical: 12,
    alignItems: 'center',
  },
  buttonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
  },
  secondaryButtonText: {
    color: '#BF8ED4',
    fontSize: 16,
    fontWeight: '600',
  },
};
